# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: Ubuntuagent
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'NPM Install'  

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: 'NPM Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publishing artifacts'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'usaini (ebaa713e-506e-4a7a-a2fd-e1454428bc1a)'
    appType: 'webApp'
    WebAppName: 'reactjs'
    packageForLinux: '$(System.DefaultWorkingDirectory)/_ReactBased-CI/drop'